version: '3'
services:
    web:
        image: nginx:1.23
        volumes:
          - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./app:/app
        ports:
            - "80:80"
        depends_on:
            - php
            - mysql
    php:
        build: 
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:10.7.8
        environment:
            MARIADB_ROOT_PASSWORD: 'secret'
            MARIADB_USER: 'example-user'
            MARIADB_PASSWORD: 'my_cool_secret'
            MARIADB_DATABASE: 'samplevideo_db'
        volumes:
            # Init is happened only on first start of container, to reinit - 'docker compose rm'
            - ./config/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - 3306:3306