version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
          - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./app:/app
        ports:
            - "80:80"
        depends_on:
            - php
            - mysql
    php:
        image: php:fpm
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        ports:
            - 3306:3306